---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  labels:
    app.kubernetes.io/name: glance
  namespace: {{ .Release.Namespace }}
data:
  glance.yaml: |
    branding:
      logo-url: https://raw.githubusercontent.com/aisling136/homelab/main/.icons/aisling.png
      favicon-url: https://raw.githubusercontent.com/aisling136/homelab/main/.icons/aisling.png
      custom-footer: |
        <p></p>
    theme:
      background-color: 50 1 6
      primary-color: 24 97 58
      negative-color: 209 88 54
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: clock
                hour-format: 24h
              - type: weather
                location: Ravena, New York, United States
                hour-format: 24h
              - type: repository
                repository: aisling136/homelab
                pull-requests-limit: 5
                issues-limit: -1
                commits-limit: -1
              - type: bookmarks
                groups:
                  - links:
                    - title: Homepage
                      url: https://home.aisling.dev/
          - size: full
            widgets:
              - type: videos
                collapse-after-rows: 3
                style: grid-cards
                channels:
                  - UCNvsIonJdJ5E4EXMa65VYpA
                  - UCvlj0IzjSnNoduQF0l3VGng
                  - UC-_AkLn4A5iBr6BXN6waR_Q
                  - UCXGR70CkW_pXb8n52LzCCRw
                  - UCRIZtPl9nb9RiXc9btSTQNw
                  - UCxAS_aK7sS2x_bqnlJHDSHw
              - type: group
                widgets:
                  - type: reddit
                    subreddit: homelab
                    show-thumbnails: true
                    collapse-after: 6
                  - type: reddit
                    subreddit: homeserver
                    show-thumbnails: true
                    collapse-after: 6
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true
                    collapse-after: 6
                  - type: reddit
                    subreddit: devops
                    show-thumbnails: true
                    collapse-after: 6
                  - type: reddit
                    subreddit: sysadmin
                    show-thumbnails: true
                    collapse-after: 6
