gateway-helm:
  config:
    envoyGateway:
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
gateways:
  - name: aisling-dev-internal
    hostname: internal.aisling.dev
    ip: 192.168.3.240
    tlsSecret: aisling-dev-tls
  - name: aisling-dev-external
    hostname: external.aisling.dev
    ip: 192.168.3.243
    tlsSecret: aisling-dev-tls
